# Generated by Django 5.2.8 on 2025-11-17 22:25

import django.core.validators
import django.db.models.deletion
import recursos_humanos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje_cotizacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_apv', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'cpt_afp',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'cpt_contacto',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'cpt_departamento',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fonasa', 'Fonasa'), ('isapre', 'Isapre')], default='fonasa', max_length=20)),
                ('nombre_isapre', models.CharField(blank=True, max_length=90, null=True)),
                ('plan', models.CharField(blank=True, max_length=90, null=True)),
                ('cotizacion_porcentaje', models.FloatField(default=7.0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'cpt_salud',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('salario_base', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Salario no puede ser menor a 0')])),
                ('contrato', models.FileField(upload_to='contratos/')),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Contrato indefinido'), ('plazo_fijo', 'Contrato a plazo fijo')], default='indefinido', max_length=50)),
                ('afp', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recursos_humanos.afp')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recursos_humanos.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cpt_empleado',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.FloatField()),
                ('horas_extra', models.FloatField()),
                ('horas_ausencia', models.FloatField()),
                ('hora_llegada', models.DateTimeField()),
                ('observaciones', models.TextField(max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='recursos_humanos.empleado')),
            ],
            options={
                'db_table': 'cpt_asistencia',
            },
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('segundo_nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('apellido', models.CharField(max_length=90)),
                ('segundo_apellido', models.CharField(max_length=90)),
                ('fecha_nacimiento', models.DateField()),
                ('run', models.CharField(max_length=12, unique=True, validators=[recursos_humanos.models.validar_rut])),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('conviviente_civil', 'Conviviente civil'), ('separado_judicialmente', 'Separado(a) judicialmente'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)')], default='soltero', max_length=50)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino'), ('otro', 'otro')], default='otro', max_length=50)),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='info', to='recursos_humanos.contacto')),
            ],
            options={
                'db_table': 'cpt_informacion_personal',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='informacion_personal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='recursos_humanos.informacionpersonal'),
        ),
        migrations.CreateModel(
            name='Inzumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.TextField(max_length=90)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Remuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(max_length=500)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remuneraciones', to='recursos_humanos.empleado')),
            ],
            options={
                'db_table': 'cpt_remuneracion',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recursos_humanos.salud'),
        ),
    ]
