# Generated by Django 5.2.8 on 2025-11-17 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='afp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recursos_humanos.afp'),
        ),
    ]
