# Generated by Django 5.2.8 on 2025-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_alter_empleado_afp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_llegada',
            field=models.TimeField(),
        ),
    ]
