# Generated by Django 5.2.8 on 2025-12-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_alter_asistencia_hora_llegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuneracion',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
